apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: create-update-delete-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 5
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
  topicName: createUpdateDeleteTopic