apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticstack-argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: 2.8.0
    helm:
      releaseName: elasticsearch
  destination:
    server: "https://kubernetes.default.svc"
    namespace: elastic