apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-driver-aws-argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: secrets-store-csi-driver-provider-aws
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    targetRevision: 0.3.2
    helm:
      releaseName: secret-driver-aws-argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: secrets-store-csi-driver