apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: strimzi-kafka-operator
    repoURL: https://strimzi.io/charts/
    targetRevision: 0.35.0
    helm:
      releaseName: strimzi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kafka
  syncPolicy:
    syncOptions:
      - CreateNamespace=true